name: ci_commit_checker
on:
  pull_request:
    types: [closed]

jobs:
  ci_commit_checker:
    if: github.event.ref == 'refs/heads/develop' && github.repository_owner == 'ockam-network' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    environment:
      name: contributors
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@a3b37769d28120b0a633f6985f454bbc6293c946
        with:
          token: ${{ secrets.CONTRIBUTORS_PAT }}
          repository: ockam-network/ockam
          event-type: commit_sig_check
          client-payload: '{"user": "${{ github.actor }}"}'
